#!/bin/bash

# Notion Workspace Setup Script for Fitness & Nutrition Tracker
# This script helps you set up your Notion workspace with the proper structure

echo "🏗️  Setting up Notion Workspace for Fitness & Nutrition Tracker"
echo "================================================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 Step 1: Create Main Dashboard Page${NC}"
echo "1. Go to your Notion workspace"
echo "2. Create a new page called 'Fitness & Nutrition Tracker'"
echo "3. Add the following sections:"
echo "   - Project Overview"
echo "   - Quick Links"
echo "   - Current Status"
echo "   - Recent Updates"
echo ""

echo -e "${BLUE}📊 Step 2: Create Development Tasks Database${NC}"
echo "1. Create a new database called 'Development Tasks'"
echo "2. Add these properties:"
echo "   - Task (Title)"
echo "   - Status (Select: Not Started, In Progress, Review, Complete, Blocked)"
echo "   - Priority (Select: Low, Medium, High, Critical)"
echo "   - Phase (Select: Phase 1, Phase 2, Phase 3, Phase 4)"
echo "   - Category (Multi-select: Frontend, Backend, Database, API, UI/UX, Testing)"
echo "   - Assignee (Person)"
echo "   - Due Date (Date)"
echo "   - Effort (Select: XS, S, M, L, XL)"
echo ""

echo -e "${BLUE}📚 Step 3: Create API Documentation Database${NC}"
echo "1. Create a new database called 'API Endpoints'"
echo "2. Add these properties:"
echo "   - Endpoint (Title)"
echo "   - Method (Select: GET, POST, PUT, DELETE)"
echo "   - Category (Select: Auth, Meals, Recipes, Workouts, Shopping)"
echo "   - Status (Select: Active, Deprecated, Planned)"
echo "   - Parameters (Text)"
echo "   - Response (Text)"
echo "   - Example (Text)"
echo ""

echo -e "${BLUE}🔧 Step 4: Create Technical Specs Database${NC}"
echo "1. Create a new database called 'Data Models'"
echo "2. Add these properties:"
echo "   - Model (Title)"
echo "   - Fields (Text)"
echo "   - Relationships (Text)"
echo "   - Status (Select: Active, Deprecated, Planned)"
echo ""

echo -e "${BLUE}🐛 Step 5: Create Bug Tracker Database${NC}"
echo "1. Create a new database called 'Bug Tracker'"
echo "2. Add these properties:"
echo "   - Bug Title (Title)"
echo "   - Status (Select: Open, In Progress, Fixed, Closed, Won't Fix)"
echo "   - Severity (Select: Low, Medium, High, Critical)"
echo "   - Component (Select: Auth, Meals, Recipes, Workouts, Shopping, UI)"
echo "   - Reporter (Person)"
echo "   - Assignee (Person)"
echo "   - Date Reported (Date)"
echo "   - Date Fixed (Date)"
echo "   - Description (Text)"
echo ""

echo -e "${GREEN}✅ Step 6: Import Initial Data${NC}"
echo "Copy and paste the following tasks into your Development Tasks database:"
echo ""
echo "Phase 3 Tasks (Current):"
echo "- Barcode Scanning Implementation (High Priority, Backend)"
echo "- Image Recognition for Calorie Estimation (High Priority, AI)"
echo "- OpenAI Integration Enhancement (Medium Priority, AI)"
echo ""
echo "Phase 4 Tasks (Planned):"
echo "- Data Visualization Charts (Medium Priority, Frontend)"
echo "- Export Functionality (Low Priority, Backend)"
echo "- Social Features (Low Priority, Full Stack)"
echo "- Mobile App Considerations (Low Priority, Mobile)"
echo ""

echo -e "${GREEN}✅ Step 7: Set Up Templates${NC}"
echo "Create these page templates:"
echo "1. Meeting Notes Template"
echo "2. Feature Specification Template"
echo "3. Bug Report Template"
echo "4. Component Documentation Template"
echo ""

echo -e "${YELLOW}🔗 Optional: API Integration Setup${NC}"
echo "If you want to integrate with Notion API:"
echo "1. Go to https://www.notion.so/my-integrations"
echo "2. Create a new integration called 'Fitness Tracker'"
echo "3. Copy the integration token"
echo "4. Add it to your .env.local file as NOTION_API_KEY"
echo "5. Share your databases with the integration"
echo ""

echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo "Your Notion workspace is ready for project management."
echo ""
echo "Next steps:"
echo "1. Customize the databases to fit your workflow"
echo "2. Invite team members if working collaboratively"
echo "3. Set up automation rules (if using Notion Pro)"
echo "4. Consider integrating with your development tools"
echo ""
echo "📖 For detailed documentation, check the generated markdown files:"
echo "   - notion-workspace-setup.md"
echo "   - notion-component-docs.md"
echo "   - notion-api-integration.md"
echo ""
echo "Happy organizing! 🚀"
